### ISSUE TITLE
Are there any examples on how to use pax-keycloak?

### ISSUE THREAD

**Issue by tadayosi** [ops4j/org.ops4j.pax.keycloak#1]
Is it supported only on Karaf 4.2?  Does pax-keycloak-hawtio currently work only with hawtio 1.x?

**Comment by minikiller** [comment]
i also need your help on how to use pax-keycloak. I also find some examples on fuse in keycloak document. but can not run camel under karaf 2.4.2. Please give me a help. thanks!

**Comment by tadayosi** [comment]
I think this project is no longer alive. @gnodet @grgrzybek Do you think you can point to the successor project in README and archive it?

**Comment by minikiller** [comment]
@tadayosi do you have any doc to help me? i want to use pax-keycloak under camel. thanks

**Comment by tadayosi** [comment]
@minikiller This is for Hawtio but you may still find it helpful.
https://github.com/hawtio/hawtio/tree/master/examples/keycloak-integration

**Comment by minikiller** [comment]
thanks very much. I try this example https://github.com/keycloak/keycloak-quickstarts/tree/latest/fuse70/service-camel under karaf 2.4.2, but still can not succeed. do you have succeed to integration camel with keycloak?

**Comment by grgrzybek** [comment]
@tadayosi @minikiller I've changed the project, so instead of providing an integration between pax-web and keycloak, it shows how Keycloak itself provides pax-web integration.

See https://github.com/ops4j/org.ops4j.pax.keycloak

I hope this helps.
