### ISSUE TITLE
keycloak-httpservice quickstart instructions no longer work

### ISSUE THREAD

**Issue by charlesmoore99** [ops4j/org.ops4j.pax.keycloak#19]
`karaf@root()> feature:repo-add mvn:org.keycloak/keycloak-osgi-features/4.5.0.Final/xml/feature
Adding feature url mvn:org.keycloak/keycloak-osgi-features/4.5.0.Final/xml/feature
Error executing command: Error resolving artifact org.keycloak:keycloak-osgi-features:xml:feature:4.5.0.Final: [Could not find artifact org.keycloak:keycloak-osgi-featurml:feature:4.5.0.Final in central (https://repo1.maven.org/maven2/)] : mvn:org.keycloak/keycloak-osgi-features/4.5.0.Final/xml/feature
`

**Comment by grgrzybek** [comment]
Despite the fact that pax.keycloak is kind of replaced by what's available in pax.web (see changes related to ops4j/org.ops4j.pax.web#1447) https://repo1.maven.org/maven2/org/keycloak/keycloak-osgi-features/4.5.0.Final/keycloak-osgi-features-4.5.0.Final-features.xml is still available in Maven central - do you have a stack trace of this problem? It may be a temporary issue.

**Comment by charlesmoore99** [comment]
I tried this again this morning and am not getting the issue.  Closing Issue.
